// 액션 아이템 시드 풀.
//
// 진실 소스(SSoT): docs/ai_prompt/competency_action_map.md
//   - 12역량 × (주니어 3 + 시니어 3) = 72개 시드를 그대로 전사한다.
//   - 역량당 연계 강점은 map.md에 "역량 단위"로만 정의되므로(액션 단위 아님)
//     선택 시 강점 가중은 두지 않는다. 개인화는 (1) career_level 가중,
//     (2) AI 문구 재작성 단계에서 처리한다.
//
// 레거시 extras: SSoT 이전부터 노출되던 손작성 액션(TED·SQL강의 등).
//   드리프트분이지만 이미 검증·노출된 콘텐츠라 풀에 함께 유지(증축)해
//   "항상 같은 5개"가 나오지 않도록 다양성을 확보한다. level: 'any'.
//
// id 규칙 — 이 값이 곧 action_items.source_seed_id (디버깅·품질 분석 추적용):
//   - SSoT 파생:  `{code}-{level}-{index}`  예) "T-1-junior-2"  (스키마 예시와 일치)
//   - 레거시 extra: `{code}-extra-{n}`        예) "T-1-extra-1"
//   ⚠ 표시 순서(몇 번째 카드)와 무관한 "어떤 시드냐"를 가리키는 안정 키여야 한다.
//      (과거엔 display-index 기반이라 풀에서 5개를 뽑으면 의미가 깨졌음 → 정정)

// 액션 화면에 노출하는 추천 개수. route 캡 · page 선택/폴백 · 프롬프트 pickCount가 공유한다.
export const ACTION_DISPLAY_COUNT = 5;

export type SeedLevel = 'junior' | 'senior' | 'any';

// 포맷/소요 버킷 — 선택 시 5개의 형식 다양성(빠른 것/깊은 것/매일 습관)을 보장하는 데 쓴다.
export type SeedEffort = 'quick' | 'deep' | 'habit';

export interface ActionItem {
  id: string; // 안정 시드 식별자 = source_seed_id
  title: string;
  description: string;
  tags: string[];
  level: SeedLevel;
  effort: SeedEffort;
}

export interface ActionSeed {
  competencyId: string; // 슬러그 (예: "critical-thinking")
  code: string; // 역량 코드 (예: "T-1")
  emoji: string;
  items: ActionItem[];
}

export const ACTION_SEEDS: ActionSeed[] = [
  // ── T | 전략적사고 ────────────────────────────────────────
  {
    competencyId: 'critical-thinking',
    code: 'T-1',
    emoji: '🧠',
    items: [
      // SSoT — 주니어
      {
        id: 'T-1-junior-1',
        title: '하루 1개 뉴스·보고서 읽고 "이 주장의 근거는?" 메모하기',
        description: '읽은 글에서 주장과 근거를 직접 짚어보며 수동적 소비를 능동적 분석으로 바꿔요.',
        tags: ['⏱ 매일', '📝 메모'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'T-1-junior-2',
        title: '읽은 자료에서 사실(Fact)과 의견(Opinion) 구분해 표시하기',
        description: '정보를 사실과 의견으로 나눠 표시하며 논리와 감정을 분리하는 기초를 익혀요.',
        tags: ['⏱ 30분', '🔍 분석'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'T-1-junior-3',
        title: '이번 주 내린 결정 1개 되돌아보고 "놓친 관점은?" 기록하기',
        description: '내 결정을 다시 보며 놓친 관점을 찾아 사고의 맹점을 인식해요.',
        tags: ['⏱ 30분', '🪞 회고'],
        level: 'junior',
        effort: 'quick',
      },
      // SSoT — 시니어
      {
        id: 'T-1-senior-1',
        title: '팀 결정 1개에 반론 3가지를 작성하고 검토 요청하기',
        description: '팀 결정에 반론 세 가지를 만들어 공유하며 조직 단위 비판적 사고를 연습해요.',
        tags: ['⏱ 1~2시간', '💬 검토'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'T-1-senior-2',
        title: '회의에서 "이 전제가 맞는지 확인해봤나요?" 최소 1번 제기하기',
        description: '회의에 깔린 전제를 한 번씩 짚어 집단사고를 막아요.',
        tags: ['💬 회의', '🙋 발언'],
        level: 'senior',
        effort: 'habit',
      },
      {
        id: 'T-1-senior-3',
        title: '한 달간 주요 결정 3개를 모아 패턴 분석하고 개선점 도출하기',
        description: '한 달간의 결정을 모아 패턴을 분석하고 의사결정을 메타적으로 점검해요.',
        tags: ['⏱ 1~2시간', '📊 분석'],
        level: 'senior',
        effort: 'deep',
      },
      // 레거시 extras
      {
        id: 'T-1-extra-1',
        title: 'TED 강연 1개 보고 핵심 논지와 근거 분석하기',
        description: '강연 하나를 보고 주장과 근거를 써보는 연습이에요.',
        tags: ['⏱ 1~2시간', '🆓 무료', '📝 분석'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'T-1-extra-2',
        title: '신문 칼럼 읽고 반론 메모 3줄 써보기',
        description: '내 생각과 다른 칼럼을 골라 읽고, 논리적으로 반박해봐요.',
        tags: ['⏱ 30분', '✍️ 글쓰기', '매일 가능'],
        level: 'any',
        effort: 'quick',
      },
      {
        id: 'T-1-extra-3',
        title: '주변 의견에 "왜?" 라고 묻는 연습 매일 1회',
        description: '당연하게 받아들이는 주장에 "그 근거는?"을 물어봐요.',
        tags: ['⏱ 습관', '💬 대화'],
        level: 'any',
        effort: 'habit',
      },
      {
        id: 'T-1-extra-4',
        title: '책 "생각에 관한 생각" 1~2장 읽기',
        description: '대니얼 카너먼의 책으로 인지 편향과 비판적 사고의 기초를 배울 수 있어요.',
        tags: ['📚 독서', '⏱ 1~2시간'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'T-1-extra-5',
        title: '케이스 스터디 1개 분석하고 내 의견 정리하기',
        description: '"내라면 어떻게 했을까?"를 논리적으로 써봐요.',
        tags: ['⏱ 1~2시간', '📄 분석', '주 1회'],
        level: 'any',
        effort: 'deep',
      },
    ],
  },
  {
    competencyId: 'data-analysis',
    code: 'T-2',
    emoji: '📊',
    items: [
      {
        id: 'T-2-junior-1',
        title: '내 업무에서 숫자로 표현할 수 있는 지표 1개 찾아 매일 기록하기',
        description: '업무 속 지표 하나를 정해 매일 기록하며 데이터 감각을 길러요.',
        tags: ['⏱ 매일', '📋 추적'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'T-2-junior-2',
        title: '보고서 차트 1개 골라 "이 데이터가 말하는 것은?" 한 문장으로 해석하기',
        description: '차트 하나를 골라 한 문장으로 해석하며 데이터 읽기의 기초를 익혀요.',
        tags: ['⏱ 30분', '🔍 해석'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'T-2-junior-3',
        title: '의사결정 전 "이걸 뒷받침하는 데이터가 있나?" 스스로 묻는 루틴 만들기',
        description: '결정하기 전 근거 데이터를 스스로 묻는 습관으로 데이터 기반 사고를 길러요.',
        tags: ['⏱ 습관', '💭 루틴'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'T-2-senior-1',
        title: '팀 주요 지표 3개를 선정하고 주간 트렌드를 1페이지로 정리해 공유하기',
        description: '핵심 지표 세 개의 주간 추이를 한 장으로 정리해 팀과 공유해요.',
        tags: ['⏱ 1~2시간', '📈 시각화'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'T-2-senior-2',
        title: '현재 업무의 비효율을 데이터로 증명하고 개선 제안서 작성하기',
        description: '비효율을 데이터로 증명해 개선 제안서로 문제를 정의해요.',
        tags: ['⏱ 1~2시간', '📄 제안'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'T-2-senior-3',
        title: '타 팀·업계 데이터와 우리 데이터를 비교해 인사이트 1개 도출하기',
        description: '우리 데이터를 외부와 비교해 인사이트를 하나 뽑아요.',
        tags: ['⏱ 1~2시간', '🔬 비교분석'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'T-2-extra-1',
        title: 'SQL 기초 강의 1~3강 완강하기',
        description: 'SELECT부터 JOIN까지 기초를 익혀요.',
        tags: ['💻 실습', '🆓 무료', '⏱ 3~4시간'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'T-2-extra-2',
        title: '엑셀 피벗 테이블로 데이터 정리 실습하기',
        description: '업무 데이터를 피벗 테이블로 분석해봐요.',
        tags: ['📊 엑셀', '⏱ 1~2시간'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'T-2-extra-3',
        title: '공개 데이터셋 1개 다운로드해 EDA 해보기',
        description: 'Kaggle에서 데이터를 받아 기본 통계를 살펴봐요.',
        tags: ['🔍 탐색', '🆓 무료', '⏱ 2~3시간'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'T-2-extra-4',
        title: '구글 데이터 스튜디오로 시각화 대시보드 만들기',
        description: '스프레드시트를 연결해 간단한 차트 대시보드를 만들어봐요.',
        tags: ['📈 시각화', '🆓 무료', '⏱ 2시간'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'T-2-extra-5',
        title: '업무에서 매일 확인하는 지표 1개 정해서 추적하기',
        description: '내가 영향을 줄 수 있는 지표를 정하고 일주일 추이를 기록해봐요.',
        tags: ['📋 추적', '⏱ 매일 5분'],
        level: 'any',
        effort: 'habit',
      },
    ],
  },
  {
    competencyId: 'planning',
    code: 'T-3',
    emoji: '🗺️',
    items: [
      {
        id: 'T-3-junior-1',
        title: '이번 주 맡은 일 하나를 목표-과제-일정 3단계로 1페이지 정리하기',
        description: '맡은 일을 목표·과제·일정으로 쪼개 한 장으로 정리하며 기획 구조를 익혀요.',
        tags: ['⏱ 1~2시간', '📄 문서화'],
        level: 'junior',
        effort: 'deep',
      },
      {
        id: 'T-3-junior-2',
        title: '아이디어 1개를 "문제-해결방안-기대효과" 구조로 써보기',
        description: '떠오른 아이디어를 문제·해결·기대효과 순으로 적어 논리적 제안을 연습해요.',
        tags: ['⏱ 30분', '✍️ 글쓰기'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'T-3-junior-3',
        title: '3개월 후 이루고 싶은 것 1개를 역순 분해해 이번 주 할 일 뽑기',
        description: '목표에서 거꾸로 내려와 이번 주 할 일을 정하는 백캐스팅을 연습해요.',
        tags: ['⏱ 30분', '🎯 계획'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'T-3-senior-1',
        title: '팀 분기 목표 달성을 위한 실행 로드맵을 마일스톤 포함해 작성하기',
        description: '분기 목표를 마일스톤이 있는 로드맵으로 그려 조직 단위 기획을 해봐요.',
        tags: ['⏱ 1~2시간', '🗺️ 로드맵'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'T-3-senior-2',
        title: '진행 중인 프로젝트 리스크 3개를 사전 정의하고 대응 방안 설계하기',
        description: '프로젝트 리스크 세 가지를 미리 정의하고 대응책을 설계해요.',
        tags: ['⏱ 1~2시간', '⚠️ 리스크'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'T-3-senior-3',
        title: '타 팀·업계 사례 1개를 우리 맥락에 맞게 재설계하는 기획안 작성하기',
        description: '좋은 사례 하나를 우리 상황에 맞게 바꿔보며 벤치마킹 기획을 연습해요.',
        tags: ['⏱ 1~2시간', '🔁 벤치마킹'],
        level: 'senior',
        effort: 'deep',
      },
    ],
  },
  // ── I | 영향력 ───────────────────────────────────────────
  {
    competencyId: 'communication',
    code: 'I-1',
    emoji: '🗣️',
    items: [
      {
        id: 'I-1-junior-1',
        title: '이메일·메시지 1개를 "결론 먼저, 이유 나중" 순서로 써보기',
        description: '결론을 먼저 쓰는 두괄식으로 메시지를 정리하는 습관을 들여요.',
        tags: ['⏱ 30분', '✍️ 글쓰기'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'I-1-junior-2',
        title: '대화 중 상대 말을 끝까지 듣고 "~라고 이해했어요"로 확인하기',
        description: '상대 말을 끝까지 듣고 되짚어 확인하며 경청 습관을 만들어요.',
        tags: ['👂 경청', '💬 대화'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'I-1-junior-3',
        title: '어려운 개념을 동료에게 3분 안에 설명해보기',
        description: '어려운 개념을 3분 안에 설명하며 설명력과 언어 명확성을 길러요.',
        tags: ['⏱ 30분', '🧑‍🏫 설명'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'I-1-senior-1',
        title: '임원·이해관계자 보고 시 "한 문장 결론 + 3가지 근거" 구조로 준비하기',
        description: '결론 한 문장과 근거 세 가지 구조로 고위 보고를 설계해요.',
        tags: ['⏱ 1~2시간', '📊 보고'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'I-1-senior-2',
        title: '팀 내 소통 문제점 1개를 찾아 개선 제안을 공유하기',
        description: '팀 소통의 문제 하나를 찾아 개선안을 제안해요.',
        tags: ['💬 소통', '📄 제안'],
        level: 'senior',
        effort: 'quick',
      },
      {
        id: 'I-1-senior-3',
        title: '다른 직군 동료에게 내 업무를 그 직군 언어로 설명해보기',
        description: '상대 직군의 언어로 내 일을 설명하며 크로스펑셔널 소통을 연습해요.',
        tags: ['🤝 협업', '🧑‍🏫 설명'],
        level: 'senior',
        effort: 'quick',
      },
      {
        id: 'I-1-extra-1',
        title: '유명 발표 영상 1개 보고 구조와 전달 방식 분석하기',
        description: 'TED를 보고 도입·본론·마무리 구조를 살펴봐요.',
        tags: ['🎙️ 발표', '⏱ 1시간', '🆓 무료'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'I-1-extra-2',
        title: '1분 자기소개 스크립트 작성하고 다듬기',
        description: '면접·네트워킹 자리에서 바로 꺼낼 수 있는 자기소개를 만들어봐요.',
        tags: ['📝 글쓰기', '⏱ 1시간'],
        level: 'any',
        effort: 'quick',
      },
      {
        id: 'I-1-extra-3',
        title: '주 1회 짧은 블로그 글 작성하기',
        description: '배운 것, 생각한 것을 500자 이상 정리해봐요.',
        tags: ['✍️ 글쓰기', '주 1회'],
        level: 'any',
        effort: 'habit',
      },
      {
        id: 'I-1-extra-4',
        title: '팀 미팅에서 먼저 발언하기 주 3회 도전',
        description: '회의에서 가장 먼저 말하는 연습을 해봐요.',
        tags: ['🙋 발언', '주 3회', '💪 도전'],
        level: 'any',
        effort: 'habit',
      },
      {
        id: 'I-1-extra-5',
        title: '동료에게 내 발표·발언에 대한 피드백 요청하기',
        description: '"제 발표에서 아쉬운 부분이 있었나요?" 라고 먼저 물어봐요.',
        tags: ['💬 피드백', '🤝 협업'],
        level: 'any',
        effort: 'quick',
      },
    ],
  },
  {
    competencyId: 'leadership',
    code: 'I-2',
    emoji: '🧭',
    items: [
      {
        id: 'I-2-junior-1',
        title: '팀 프로젝트에서 작은 역할 하나를 먼저 자처하고 끝까지 책임지기',
        description: '작은 역할을 먼저 맡아 끝까지 책임지며 소규모 리더십을 경험해요.',
        tags: ['🙋 자처', '💪 책임'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'I-2-junior-2',
        title: '회의에서 "우리가 지금 해결하려는 문제가 뭔가요?"를 먼저 묻기',
        description: '회의에서 해결할 문제를 먼저 물어 방향을 잡는 질문을 연습해요.',
        tags: ['💬 회의', '❓ 질문'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'I-2-junior-3',
        title: '팀원 1명에게 이번 주 잘한 점을 구체적으로 말해주기',
        description: '팀원의 잘한 점을 구체적으로 전하며 강점 기반 인정 습관을 들여요.',
        tags: ['💬 인정', '🌟 강점'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'I-2-senior-1',
        title: '결정 1개를 팀원에게 완전히 위임하고 결과보다 과정에 피드백 주기',
        description: '결정 하나를 완전히 위임하고 과정에 피드백하며 신뢰를 설계해요.',
        tags: ['🤝 위임', '💬 피드백'],
        level: 'senior',
        effort: 'quick',
      },
      {
        id: 'I-2-senior-2',
        title: '한 달 후 팀의 모습을 비전으로 그리고 팀과 공유하기',
        description: '한 달 뒤 팀의 모습을 비전으로 그려 공유하며 방향을 제시해요.',
        tags: ['⏱ 1~2시간', '🔭 비전'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'I-2-senior-3',
        title: '팀원 강점을 파악하고 다음 프로젝트 역할을 강점 기반으로 배치하기',
        description: '팀원의 강점을 파악해 다음 역할을 강점 기반으로 배치해요.',
        tags: ['⏱ 1~2시간', '🌟 강점'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'I-2-extra-1',
        title: '팀원 1명과 1:1 미팅 잡기',
        description: '15~30분 짧은 1:1 미팅으로 팀원의 고민을 듣고 지지해봐요.',
        tags: ['🤝 관계', '⏱ 30분', '주 1회'],
        level: 'any',
        effort: 'quick',
      },
      {
        id: 'I-2-extra-2',
        title: '"팀이 나아갈 방향" 1페이지 문서 써보기',
        description: '지금 맡은 일의 목적과 방향을 한 장으로 정리해봐요.',
        tags: ['📄 문서화', '⏱ 1시간'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'I-2-extra-3',
        title: '팀원에게 긍정적인 피드백 주 3회 전달하기',
        description: '어떤 부분이 좋았고 왜 의미있었는지 구체적으로 전달해봐요.',
        tags: ['💬 피드백', '주 3회'],
        level: 'any',
        effort: 'habit',
      },
      {
        id: 'I-2-extra-4',
        title: '리더십 관련 책 1챕터 읽고 내 상황에 적용해보기',
        description: '"팀장의 탄생" 같은 책으로 시작해봐요.',
        tags: ['📚 독서', '⏱ 1~2시간'],
        level: 'any',
        effort: 'deep',
      },
      {
        id: 'I-2-extra-5',
        title: '회의 때 결론과 다음 액션을 요약해서 공유하기',
        description: '회의가 끝날 때 정리해서 팀에 공유해요.',
        tags: ['📋 정리', '💬 소통', '매일'],
        level: 'any',
        effort: 'habit',
      },
    ],
  },
  {
    competencyId: 'persuasion',
    code: 'I-3',
    emoji: '🤝',
    items: [
      {
        id: 'I-3-junior-1',
        title: '설득 시 "내 이유" 전에 "상대에게 어떤 이득인가"를 먼저 생각하기',
        description: '내 이유보다 상대의 이득을 먼저 떠올리며 상대 중심으로 설득해요.',
        tags: ['💬 대화', '🔁 습관'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'I-3-junior-2',
        title: '반대 의견을 받았을 때 "맞아요, 그리고~"로 이어가는 연습하기',
        description: '반대를 부드럽게 이어받아 갈등 없이 반론하는 법을 익혀요.',
        tags: ['💬 대화', '🤝 협상'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'I-3-junior-3',
        title: '내 제안에 숫자나 사례로 "근거 1개 추가" 습관 만들기',
        description: '제안할 때마다 숫자나 사례를 하나씩 붙여 설득력을 높여요.',
        tags: ['📊 근거', '🔁 습관'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'I-3-senior-1',
        title: '이해관계가 다른 두 팀 사이에서 공통 목표를 찾아 합의를 이끌어내기',
        description: '입장이 다른 두 팀의 공통 목표를 찾아 합의로 이끄는 다자 협상을 연습해요.',
        tags: ['⏱ 1~2시간', '🤝 협상'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'I-3-senior-2',
        title: '중요한 협의 전 BATNA(최악의 대안)와 목표 범위를 사전에 설정하기',
        description: '협의 전 최악의 대안과 목표 범위를 정해 전략적으로 준비해요.',
        tags: ['⏱ 30분', '♟️ 전략'],
        level: 'senior',
        effort: 'quick',
      },
      {
        id: 'I-3-senior-3',
        title: '성사된 협의 1개를 되돌아보고 더 나은 접근을 설계해보기',
        description: '끝난 협의를 복기하며 다음엔 어떻게 더 잘할지 설계해요.',
        tags: ['🪞 회고', '🤝 협상'],
        level: 'senior',
        effort: 'quick',
      },
    ],
  },
  // ── R | 관계구축 ─────────────────────────────────────────
  {
    competencyId: 'collaboration',
    code: 'R-1',
    emoji: '🧩',
    items: [
      {
        id: 'R-1-junior-1',
        title: '같이 일하는 사람 1명의 업무 방식을 관찰하고 장점 1가지 메모하기',
        description: '동료의 일하는 방식을 살펴 장점을 하나 적으며 타인 스타일을 이해해요.',
        tags: ['👀 관찰', '📝 메모'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'R-1-junior-2',
        title: '내가 맡은 파트 외에 팀 전체 목표를 한 문장으로 써보기',
        description: '내 일 너머 팀 전체 목표를 한 문장으로 정리해 협업 맥락을 인식해요.',
        tags: ['⏱ 30분', '🎯 맥락'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'R-1-junior-3',
        title: '어색한 팀원에게 먼저 업무 외 대화 1번 시도하기',
        description: '어색한 동료에게 먼저 가벼운 대화를 건네 관계를 넓혀요.',
        tags: ['💬 대화', '🤝 관계'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'R-1-senior-1',
        title: '팀 의견 충돌 상황에서 "우리 모두 원하는 것은~"으로 공통점 정리하기',
        description: '충돌이 생기면 모두가 원하는 공통점을 짚어 갈등을 중재해요.',
        tags: ['🕊️ 중재', '💬 회의'],
        level: 'senior',
        effort: 'habit',
      },
      {
        id: 'R-1-senior-2',
        title: '타 팀 협업 시 상대 팀의 제약 조건을 먼저 파악하고 협업 방식 제안하기',
        description: '협업 전 상대 팀의 제약을 먼저 이해하고 맞는 방식을 제안해요.',
        tags: ['⏱ 1~2시간', '🤝 협업'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'R-1-senior-3',
        title: '협업 완료 후 팀 회고를 리드하고 다음 협업 개선점 1개 도출하기',
        description: '협업이 끝나면 회고를 이끌어 다음을 위한 개선점을 하나 뽑아요.',
        tags: ['🪞 회고', '🤝 협업'],
        level: 'senior',
        effort: 'deep',
      },
    ],
  },
  {
    competencyId: 'mentoring',
    code: 'R-2',
    emoji: '🌱',
    items: [
      {
        id: 'R-2-junior-1',
        title: '누군가의 고민을 들을 때 조언 전에 판단 없이 5분간 끝까지 듣기',
        description: '조언하기 전에 판단 없이 5분간 끝까지 들으며 공감 경청을 연습해요.',
        tags: ['👂 경청', '💬 대화'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'R-2-junior-2',
        title: '내가 배운 것 1개를 동료에게 10분 안에 가르쳐보기',
        description: '배운 것을 동료에게 10분 안에 설명하며 지식 공유와 설명력을 길러요.',
        tags: ['⏱ 30분', '🧑‍🏫 공유'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'R-2-junior-3',
        title: '함께 일하는 사람의 강점 1가지를 발견하고 직접 말해주기',
        description: '동료의 강점을 하나 발견해 직접 말해주며 강점 발견·전달을 연습해요.',
        tags: ['💬 대화', '🌟 강점'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'R-2-senior-1',
        title: '후배·팀원과 월 1회 1:1 미팅을 정례화하고 성장 목표를 함께 설정하기',
        description: '팀원과 월 1회 1:1을 정하고 성장 목표를 함께 세워 멘토링을 구조화해요.',
        tags: ['🤝 1:1', '🌱 성장'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'R-2-senior-2',
        title: '팀원이 막혔을 때 답 대신 "어떻게 풀어보고 싶어요?"로 질문하기',
        description: '막힌 팀원에게 답 대신 질문을 던져 스스로 풀게 돕는 코칭을 연습해요.',
        tags: ['❓ 질문', '🌱 코칭'],
        level: 'senior',
        effort: 'habit',
      },
      {
        id: 'R-2-senior-3',
        title: '이번 분기 팀원 1명의 성장 스토리를 팀 전체에 공유하기',
        description: '팀원의 성장 이야기를 팀에 공유해 성장하는 문화를 만들어요.',
        tags: ['🗣️ 공유', '🌱 성장'],
        level: 'senior',
        effort: 'quick',
      },
    ],
  },
  {
    competencyId: 'empathy-comm',
    code: 'R-3',
    emoji: '💗',
    items: [
      {
        id: 'R-3-junior-1',
        title: '상대가 힘들어 보일 때 조언 전에 "많이 힘들었겠다"를 먼저 말하기',
        description: '조언보다 "많이 힘들었겠다"를 먼저 건네며 공감을 앞세워 소통해요.',
        tags: ['💗 공감', '💬 대화'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'R-3-junior-2',
        title: '감사한 동료 1명에게 구체적인 이유를 담아 감사를 표현하기',
        description: '고마운 동료에게 이유를 구체적으로 담아 감사를 전하며 신뢰를 쌓아요.',
        tags: ['🙏 감사', '🤝 관계'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'R-3-junior-3',
        title: '오해 상황에서 내 입장 전에 "상대는 왜 그렇게 느꼈을까?" 먼저 생각하기',
        description: '오해가 생기면 상대의 감정을 먼저 헤아리며 관점을 바꿔봐요.',
        tags: ['🔁 관점', '💗 공감'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'R-3-senior-1',
        title: '팀 분위기가 무거울 때 원인을 파악하고 전환을 위한 행동 1가지 기획하기',
        description: '무거운 팀 분위기의 원인을 찾아 분위기를 바꿀 행동을 하나 기획해요.',
        tags: ['⏱ 1~2시간', '💗 감성리더십'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'R-3-senior-2',
        title: '갈등 상황에서 양쪽 입장을 각각 들은 후 공통점 찾아 중재안 제안하기',
        description: '갈등의 양쪽을 각각 듣고 공통점을 찾아 중재안을 제안해요.',
        tags: ['🕊️ 중재', '💬 갈등'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'R-3-senior-3',
        title: '팀원의 번아웃 신호를 인식하는 체크리스트를 만들고 주기적으로 확인하기',
        description: '번아웃 신호 체크리스트를 만들어 팀의 심리 안전망을 점검해요.',
        tags: ['✅ 체크리스트', '💗 케어'],
        level: 'senior',
        effort: 'deep',
      },
    ],
  },
  // ── E | 실행력 ───────────────────────────────────────────
  {
    competencyId: 'execution',
    code: 'E-1',
    emoji: '🚀',
    items: [
      {
        id: 'E-1-junior-1',
        title: '미루고 있던 일 1개를 "완벽하지 않아도 시작"해보기',
        description: '미룬 일 하나를 완벽하지 않아도 시작하며 완벽주의를 극복해요.',
        tags: ['🚀 즉시 실행', '⏱ 오늘'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'E-1-junior-2',
        title: '하루 시작 전 반드시 할 것 3가지를 적고 하루 끝에 체크하기',
        description: '하루 할 일 세 가지를 적고 끝에 점검하며 실행 루틴을 만들어요.',
        tags: ['⏱ 매일', '📋 루틴'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'E-1-junior-3',
        title: '이번 주 목표 1개를 24시간 안에 첫 행동으로 연결해보기',
        description: '이번 주 목표 하나를 24시간 안에 첫 행동으로 옮겨 모멘텀을 만들어요.',
        tags: ['⚡ 실행', '⏱ 24시간'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'E-1-senior-1',
        title: '팀 프로젝트 지연 요인 1개를 찾아 이번 주 안에 해소 방안 실행하기',
        description: '프로젝트 지연 요인을 찾아 이번 주 안에 해소해 조직 실행력을 높여요.',
        tags: ['⏱ 1주', '⚡ 실행'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'E-1-senior-2',
        title: '불확실한 의사결정 상황에서 "일단 해보고 학습" 원칙을 팀에 제안하기',
        description: '불확실할 때 "일단 해보고 학습" 원칙을 제안해 실행 중심 문화를 만들어요.',
        tags: ['💬 제안', '🧪 실험'],
        level: 'senior',
        effort: 'quick',
      },
      {
        id: 'E-1-senior-3',
        title: '분기 목표 달성률을 점검하고 남은 기간 재조정 계획 수립하기',
        description: '분기 달성률을 점검하고 남은 기간 계획을 재조정해 실행을 관리해요.',
        tags: ['⏱ 1~2시간', '📊 점검'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'E-1-extra-1',
        title: '오늘 안에 끝낼 수 있는 작은 일 1개 바로 시작하기',
        description: '"완벽하게 준비되면"을 내려놓고, 지금 당장 첫 번째 단계를 밟아요.',
        tags: ['🚀 즉시 실행', '⏱ 오늘'],
        level: 'any',
        effort: 'quick',
      },
      {
        id: 'E-1-extra-2',
        title: '이번 주 목표 3개를 월요일 아침에 적어두기',
        description: '주 단위로 목표를 명확히 하고 금요일에 달성 여부를 확인해요.',
        tags: ['📋 계획', '주간 루틴'],
        level: 'any',
        effort: 'habit',
      },
      {
        id: 'E-1-extra-3',
        title: '미루고 있던 일 1개를 "2분 규칙"으로 처리하기',
        description: '2분 안에 끝낼 수 있는 일은 지금 바로 해요.',
        tags: ['⚡ 즉시 실행', '💡 습관'],
        level: 'any',
        effort: 'quick',
      },
      {
        id: 'E-1-extra-4',
        title: '프로젝트 아이디어를 72시간 안에 첫 단계 실행하기',
        description: '아이디어가 생기면 72시간 안에 딱 한 가지 행동을 해요.',
        tags: ['🎯 실행', '⏱ 72시간'],
        level: 'any',
        effort: 'quick',
      },
      {
        id: 'E-1-extra-5',
        title: '매일 저녁 5분, 오늘 한 일 3줄 회고하기',
        description: '오늘 실행한 것, 못 한 것, 내일 할 것을 짧게 적어요.',
        tags: ['📝 회고', '⏱ 5분', '매일'],
        level: 'any',
        effort: 'habit',
      },
    ],
  },
  {
    competencyId: 'problem-solving',
    code: 'E-2',
    emoji: '🛠️',
    items: [
      {
        id: 'E-2-junior-1',
        title: '이번 주 발생한 문제 1개를 "원인-영향-해결안" 3단계로 정리하기',
        description: '생긴 문제를 원인·영향·해결안으로 나눠 구조적으로 분석해요.',
        tags: ['⏱ 30분', '🔍 분석'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'E-2-junior-2',
        title: '막힌 일이 생겼을 때 "지금 당장 내가 할 수 있는 것 1가지"를 먼저 찾기',
        description: '막히면 통제 가능한 한 가지부터 찾아 바로 움직여요.',
        tags: ['⚡ 실행', '🔁 습관'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'E-2-junior-3',
        title: '이번 주 실수 1개를 "다음엔 어떻게?"로 전환해 기록하기',
        description: '실수를 "다음엔 어떻게"로 바꿔 적으며 실패를 학습으로 전환해요.',
        tags: ['🪞 회고', '📝 기록'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'E-2-senior-1',
        title: '반복되는 팀 문제 1개를 근본 원인까지 파고들어 구조적 해결책 제안하기',
        description: '되풀이되는 문제의 근본 원인까지 파고들어 구조적 해결책을 제안해요.',
        tags: ['⏱ 1~2시간', '🔍 근본원인'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'E-2-senior-2',
        title: '프로젝트 착수 전 예상 리스크 3개를 정의하고 대응 시나리오 설계하기',
        description: '시작 전에 리스크 세 가지를 정의하고 대응 시나리오를 설계해요.',
        tags: ['⚠️ 리스크', '♟️ 선제대응'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'E-2-senior-3',
        title: '이번 분기 해결한 주요 문제 2개를 사례로 정리해 팀에 공유하기',
        description: '해결한 문제 두 개를 사례로 정리해 팀에 지식으로 남겨요.',
        tags: ['🗂️ 사례', '🗣️ 공유'],
        level: 'senior',
        effort: 'deep',
      },
    ],
  },
  {
    competencyId: 'self-management',
    code: 'E-3',
    emoji: '⏳',
    items: [
      {
        id: 'E-3-junior-1',
        title: '에너지가 높은 시간대를 파악하고 가장 중요한 일을 그 시간에 배치하기',
        description: '에너지가 높은 시간을 찾아 가장 중요한 일을 거기에 배치해요.',
        tags: ['⏱ 30분', '⚡ 에너지'],
        level: 'junior',
        effort: 'quick',
      },
      {
        id: 'E-3-junior-2',
        title: '하루 집중 블록 1개(90분) 설정하고 그 시간엔 알림 끄기',
        description: '하루 90분 집중 블록을 정하고 알림을 꺼 딥워크를 연습해요.',
        tags: ['🎯 집중', '⏱ 매일'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'E-3-junior-3',
        title: '하루 끝에 "에너지를 뺏어간 것"과 "채워준 것"을 각 1개씩 기록하기',
        description: '하루를 마치며 에너지를 뺏고 채운 것을 적어 패턴을 인식해요.',
        tags: ['📝 기록', '⚡ 에너지'],
        level: 'junior',
        effort: 'habit',
      },
      {
        id: 'E-3-senior-1',
        title: '주간 시작 전 "이번 주 하지 않을 것" 2가지를 정하고 팀에 공유하기',
        description: '한 주를 시작하며 "하지 않을 것" 두 가지를 정해 경계를 세우고 위임해요.',
        tags: ['⏱ 30분', '🚫 경계'],
        level: 'senior',
        effort: 'quick',
      },
      {
        id: 'E-3-senior-2',
        title: '분기별 나의 번아웃 신호 패턴을 기록하고 회복 루틴을 설계하기',
        description: '분기마다 번아웃 신호를 기록하고 회복 루틴을 설계해 지속가능하게 일해요.',
        tags: ['🪞 회고', '🔋 회복'],
        level: 'senior',
        effort: 'deep',
      },
      {
        id: 'E-3-senior-3',
        title: '팀 회의·보고 구조를 점검해 불필요한 시간 낭비 1개를 줄이는 제안하기',
        description: '회의·보고 구조를 점검해 시간 낭비 하나를 줄이는 제안을 해요.',
        tags: ['⏱ 1~2시간', '📈 생산성'],
        level: 'senior',
        effort: 'deep',
      },
    ],
  },
];

export const ACTION_SEEDS_BY_COMPETENCY = Object.fromEntries(
  ACTION_SEEDS.map((seed) => [seed.competencyId, seed])
);
